version: '3'

services:
  db:
    image: mysql:latest
    restart: on-failure
    container_name: bdd_proyectoP1
    environment:
      - MYSQL_DATABASE=bdd_cursos_online
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3307:3306'
    volumes:
      - ./scriptDB.sql:/docker-entrypoint-initdb.d/scriptDB.sql

